import React from 'react';


export const metadata = {
    title: 'Add Product | DashBoard | NextJs',
    description: 'Generated by next hero',
  }
const AddProductPage = () => {
    return (
        <div>
            <h1>Add Product Page</h1>
        </div>
    );
};

export default AddProductPage;