import React from 'react';


export const metadata = {
    title: 'About | NextJs',
    description: 'Generated by next hero',
  }

const about = () => {
    return (
        <div>
            THis is about page
        </div>
    );
};

export default about;