import React from 'react';
import LoginForm from './LoginForm';


export const metadata = {
    title: 'Login | NextJs',
    description: 'Generated by next hero',
  }
const LoginPage = () => {
    return (
        <div>
           <LoginForm/> 
        </div>
    );
};

export default LoginPage;