import NavBar from "@/components/NavBar";
import Toaster from "@/components/Toaster";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";

import { Providers } from "@/redux/provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJs",
  description: "Generated by next hero",
};

 const RootLayout =({ children }) =>{
  return (
    <html lang="en">
      <body className={inter.className}>
    
        
      <Providers><NavBar/> {children}   <Footer/>  </Providers>

     
         
   
     
       <Toaster />
      </body>

    </html>
  );
}
export default RootLayout;

