import React from 'react';

export const metadata = {
    title: 'DashBoard | NextJs',
    description: 'Generated by next hero',
  }


const DashBoardPage = () => {
    return (
        <div>
            <h1>Dash Board page</h1>
        </div>
    );
};

export default DashBoardPage;